// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.js");
var Goap$ReasonGoap = require("../src/Goap.bs.js");

var worldState = /* :: */[
  /* record */[
    /* name */"Scale is Blue",
    /* value : false */0
  ],
  /* :: */[
    /* record */[
      /* name */"Scale is Red",
      /* value : false */0
    ],
    /* :: */[
      /* record */[
        /* name */"Red Switch Owned",
        /* value : false */0
      ],
      /* :: */[
        /* record */[
          /* name */"Blue Switch Owned",
          /* value : false */0
        ],
        /* :: */[
          /* record */[
            /* name */"Is at HP",
            /* value : false */0
          ],
          /* :: */[
            /* record */[
              /* name */"Has Cube",
              /* value : false */0
            ],
            /* [] */0
          ]
        ]
      ]
    ]
  ]
];

var goalState = /* :: */[
  /* record */[
    /* name */"Scale is Blue",
    /* value : true */1
  ],
  /* :: */[
    /* record */[
      /* name */"Scale is Red",
      /* value : false */0
    ],
    /* :: */[
      /* record */[
        /* name */"Red Switch Owned",
        /* value : false */0
      ],
      /* :: */[
        /* record */[
          /* name */"Blue Switch Owned",
          /* value : false */0
        ],
        /* :: */[
          /* record */[
            /* name */"Is at HP",
            /* value : false */0
          ],
          /* :: */[
            /* record */[
              /* name */"Has Cube",
              /* value : false */0
            ],
            /* [] */0
          ]
        ]
      ]
    ]
  ]
];

var actions = /* :: */[
  /* record */[
    /* name */"Score on Blue Scale",
    /* preconditions : :: */[
      /* record */[
        /* name */"Has Cube",
        /* value : true */1
      ],
      /* [] */0
    ],
    /* results : :: */[
      /* record */[
        /* name */"Has Cube",
        /* value : false */0
      ],
      /* :: */[
        /* record */[
          /* name */"Scale is Blue",
          /* value : true */1
        ],
        /* [] */0
      ]
    ],
    /* cost */5
  ],
  /* :: */[
    /* record */[
      /* name */"Get Cube From HP",
      /* preconditions : :: */[
        /* record */[
          /* name */"Has Cube",
          /* value : false */0
        ],
        /* [] */0
      ],
      /* results : :: */[
        /* record */[
          /* name */"Has Cube",
          /* value : true */1
        ],
        /* [] */0
      ],
      /* cost */5
    ],
    /* :: */[
      /* record */[
        /* name */"Get Cube From Pile",
        /* preconditions : :: */[
          /* record */[
            /* name */"Has Cube",
            /* value : false */0
          ],
          /* [] */0
        ],
        /* results : :: */[
          /* record */[
            /* name */"Has Cube",
            /* value : true */1
          ],
          /* [] */0
        ],
        /* cost */3
      ],
      /* [] */0
    ]
  ]
];

describe("find path", (function () {
        return Jest.test("assert a plan was created", (function () {
                      var match = Goap$ReasonGoap.planDFS(actions, worldState, goalState, 10, /* [] */0);
                      console.log(match[0]);
                      return Jest.Expect[/* toEqual */12](/* tuple */[
                                  8,
                                  /* true */1
                                ], Jest.Expect[/* expect */0](/* tuple */[
                                      match[1],
                                      match[2]
                                    ]));
                    }));
      }));

exports.worldState = worldState;
exports.goalState = goalState;
exports.actions = actions;
/*  Not a pure module */
